# -*- coding: utf-8 -*-
"""heart_disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14rBj4MyEMhnVOG7-9ufgtGMrbWCKY6UT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('heart.csv')

data

data.head(5)

data.tail(5)

data.shape

data.info()

data.isnull().sum()

data.describe()

data['sex'].value_counts()

pd.crosstab(data.target, data.sex)

pd.crosstab(data.target,data.sex).plot(kind="bar")
plt.title("Heart disease frequency for sex")
plt.xlabel("0 = No Disease, 1 = Disease")
plt.ylabel("Amount")
plt.legend(["Female", "Male"])
plt.xticks(rotation = 0)

plt.figure(figsize=(10,6))
plt.scatter(data.age[data.target==1],data.thalach[data.target == 1], c="red")
plt.scatter(data.age[data.target==0],data.thalach[data.target == 0], c="green")

plt.title("Heart Disease in function of Age and Max Heart Rate")
plt.xlabel("Age")
plt.ylabel("Heart Rate")
plt.legend(["Disease", "No Disease"])

data["age"][data["target"] == 1]

pd.crosstab(data.cp,data.target).plot(kind="bar")

plt.title("Heart Disease frequency per chest pain type")
plt.xlabel("Chest Pain Type")
plt.ylabel("Amount")
plt.legend(["No Disease", "Disease"])
plt.xticks(rotation=0)

import seaborn as sns
corr=data.corr()
plt.figure(figsize=(15,15))
sns.heatmap(corr,annot=True)

corr

sns.set_style('whitegrid')
sns.countplot(x = 'target', data = data)

dataset=data.copy()
dataset.head()

X=dataset.drop(['target'], axis = 1)
y = dataset['target']

X.columns

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train, y_train)

prediction = model.predict(X_test)
prediction[:10]

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediction)

from sklearn.metrics import accuracy_score
print(f"Accuracy of model is {round(accuracy_score(y_test, prediction)*100, 2)}%")

import pickle
pickle.dump(model,open('model.pkl','wb'))